import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="flex gap-6 px-6 py-4 border-b border-gray-200">
          <link href = "/" className= "hover:underline"></link>
          <link href = "/about" className = "hover:underline"></link>
          <link href = "/login" className= "hover:underline"></link>
        </nav>

        <main className="flex-1 p-6">
          {children}
        </main>
      </body>
    </html>
  );
}
